export const metadata = {
  title: 'Aqua Foundation',
  description: 'Generated by emmycoder',
  icons: {
    icon: '/logo.png',
    shortcut: '/logo.png',
    apple: '/logo.png',
    // Optional: Add other sizes
    other: {
      rel: 'apple-touch-icon-precomposed',
      url: '/logo.png',
  }
}
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body>{children}</body>
    </html>
  )
}

